### ISSUE TITLE
PHP warning when SEO module is added to fresh pluck 4.7.15 installation

### ISSUE THREAD

**Issue by Rolandbaba** [pluck-cms/pluck#97] opened 2021-01-12 03:01 UTC
Hello,

I just added latest SEO module (0.4) do a fresh installation of pluck and got the following PHP notice:

`Notice: Trying to access array offset on value of type null in DOCUMENTROOT/data/modules/seo/seo.php on line 24`

Some test showed, that accessing the global `$lang` array from within SEO module is impossible.

It seems cause by declaration of any function named `*_url_prefix` within `seo.php. $lang` is only accessible, if all those functions are removed.

Regards

**Comment by BSteelooper** [comment] 2021-02-09 08:54
Are you using php 7.4?

**Comment by BSteelooper** [comment] 2021-02-12 12:52
The problem is in the line 
'author'        => $lang['general']['pluck_dev_team'],

when I print the vars which are available I see the first 4 openings of the page the lang global variable is not yet available 

I'll close this issue and continue in you issue in de module page.

**Closed by BSteelooper** 2021-02-12 12:52 UTC
